version: '3.8'

services:  pegasus:
    build: .
    command: ["npm", "run", "start:prod"]
    ports:
      - "3000:3000"    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Persist generated plugins
      - generated_plugins:/app/generated
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  generated_plugins:
    driver: local
